spring.application.name=spacz
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/spacz?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable Hibernate's second-level cache (optional, but can improve performance)
spring.cache.type=simple
