-- H2 test profile: the rows Flyway seeds in PostgreSQL (V4 amenities, V5 programs), in the same order so IDs match.
INSERT INTO amenities (code, name, icon, description, active) VALUES
    ('WIFI', 'Wi-Fi', 'wifi', 'High-speed internet', TRUE),
    ('AC', 'Air Conditioning', 'snowflake', 'Fully air-conditioned hall', TRUE),
    ('POWER_BACKUP', 'Power Backup', 'battery', 'Generator / inverter backup', TRUE),
    ('CHARGING', 'Charging Points', 'plug', 'Power socket at every seat', TRUE),
    ('LOCKER', 'Personal Locker', 'lock', 'Lockable storage', TRUE),
    ('WATER', 'Drinking Water', 'droplet', 'RO drinking water', TRUE),
    ('WASHROOM', 'Clean Washrooms', 'restroom', 'Separate, cleaned daily', TRUE),
    ('CCTV', 'CCTV Security', 'camera', '24x7 CCTV surveillance', TRUE),
    ('PARKING', 'Parking', 'car', 'Two-wheeler / car parking', TRUE),
    ('LIBRARY', 'Reference Library', 'book', 'Books and magazines', TRUE),
    ('DISCUSSION', 'Discussion Room', 'users', 'Group study room', TRUE),
    ('CAFETERIA', 'Cafeteria', 'coffee', 'Tea, coffee and snacks', TRUE),
    ('PRINTER', 'Printing', 'printer', 'Print and photocopy', TRUE),
    ('READING_LAMP', 'Reading Lamp', 'lamp', 'Individual desk lamp', TRUE),
    ('NEWSPAPER', 'Daily Newspapers', 'newspaper', 'Daily newspapers', TRUE);
INSERT INTO programs (code, name, category, active, created_at, updated_at) VALUES
    ('UPSC_CSE', 'UPSC Civil Services', 'Civil Services', TRUE, now(), now()),
    ('STATE_PSC', 'State PSC', 'Civil Services', TRUE, now(), now()),
    ('SSC_CGL', 'SSC CGL', 'Government Jobs', TRUE, now(), now()),
    ('SSC_CHSL', 'SSC CHSL', 'Government Jobs', TRUE, now(), now()),
    ('RRB_NTPC', 'RRB NTPC', 'Government Jobs', TRUE, now(), now()),
    ('IBPS_PO', 'IBPS PO', 'Banking', TRUE, now(), now()),
    ('SBI_PO', 'SBI PO', 'Banking', TRUE, now(), now()),
    ('IBPS_CLERK', 'IBPS Clerk', 'Banking', TRUE, now(), now()),
    ('GATE', 'GATE', 'Engineering', TRUE, now(), now()),
    ('JEE_MAIN', 'JEE Main', 'Engineering', TRUE, now(), now()),
    ('JEE_ADV', 'JEE Advanced', 'Engineering', TRUE, now(), now()),
    ('NEET_UG', 'NEET UG', 'Medical', TRUE, now(), now()),
    ('NEET_PG', 'NEET PG', 'Medical', TRUE, now(), now()),
    ('CAT', 'CAT', 'Management', TRUE, now(), now()),
    ('CA', 'Chartered Accountancy', 'Professional', TRUE, now(), now()),
    ('CLAT', 'CLAT', 'Law', TRUE, now(), now()),
    ('GRE_GMAT', 'GRE / GMAT', 'Study Abroad', TRUE, now(), now()),
    ('OTHER', 'Other / Self Study', 'Other', TRUE, now(), now()),
    ('EAMCET', 'TS / AP EAMCET', 'Engineering', TRUE, now(), now());
